### PR TITLE
Update to v3.5.0

### LINKED ISSUE #1: Not building on Hirsute
This package is currently not available on 21.04, which means Tensorman can't use an NVIDIA GPU. I'm getting errors attempting to build locally:
```
jacob@pop-os:~/Work/nvidia-container-runtime$ debuild -b -uc -us
 dpkg-buildpackage -us -uc -ui -b
dpkg-buildpackage: info: source package nvidia-container-runtime
dpkg-buildpackage: info: source version 3.4.0-1pop1
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by Ian Douglas Scott <idscott@system76.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   dh_auto_clean
dh_auto_clean: warning: Compatibility levels before 10 are deprecated (level 9 in use)
	make -j1 distclean
make[1]: Entering directory '/home/jacob/Work/nvidia-container-runtime'
rm -rf /home/jacob/Work/nvidia-container-runtime/dist
make[1]: Leaving directory '/home/jacob/Work/nvidia-container-runtime'
   dh_clean
dh_clean: warning: Compatibility levels before 10 are deprecated (level 9 in use)
 debian/rules build
dh build
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   dh_update_autotools_config
   dh_auto_configure
dh_auto_configure: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/jacob/Work/nvidia-container-runtime'
ln -sTf . src/vendor/src
GOCACHE="$(pwd)/gocache" GOPATH="$(pwd)/src/vendor" make -C src build
make[2]: Entering directory '/home/jacob/Work/nvidia-container-runtime/src'
go: cannot find main module, but found Gopkg.lock in /home/jacob/Work/nvidia-container-runtime/src
	to create a module there, run:
	go mod init
make[2]: *** [Makefile:8: build] Error 1
make[2]: Leaving directory '/home/jacob/Work/nvidia-container-runtime/src'
make[1]: *** [debian/rules:11: override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/jacob/Work/nvidia-container-runtime'
make: *** [debian/rules:7: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
```
Not sure if this local error is the same one Jenkins had or not, since the Jenkins logs have long rotated out.

### PR DESCRIPTION
**Pull request by mmstick**
This should fix the packaging issues on hirsute as well

### CODE REVIEW

**Comment by jacobgkau** [comment]
b844140 is not currently installing:
```
system76@pop-os:~$ apt policy nvidia-container-runtime
nvidia-container-runtime:
  Installed: (none)
  Candidate: 3.5.0-1~1626361786~21.04~b844140
  Version table:
     3.5.0-1~1626361786~21.04~b844140 1002
       1002 http://apt.pop-os.org/staging/upstream-v3.5.0 hirsute/main amd64 Packages
system76@pop-os:~$ sudo apt install nvidia-container-runtime
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-container-toolkit : Depends: libnvidia-container-tools (>= 1.3.0) but it is not installable
                            Depends: libnvidia-container-tools (< 2.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
system76@pop-os:~$ apt policy libnvidia-container-tools
libnvidia-container-tools:
  Installed: (none)
  Candidate: (none)
  Version table:
```

**Review by jackpot51 — APPROVED** [review]
250000 lines changed, LGTM...

**Comment by jacobgkau** [comment]
This is working on Hirsute (when installed with https://github.com/pop-os/libnvidia-container/pull/4), but it doesn't build on Focal. Getting this error when trying to build locally:

```
make[2]: Entering directory '/home/system76/nvidia-container-runtime'
go build -ldflags "-s -w" ./cmd/...
# github.com/nvidia/nvidia-container-runtime/cmd/nvidia-container-runtime
cmd/nvidia-container-runtime/main.go:76:22: undefined: os.ReadFile
note: module requires Go 1.16
make[2]: *** [Makefile:32: binaries] Error 2
make[2]: Leaving directory '/home/system76/nvidia-container-runtime'
```

**Comment by mmstick** [comment]
That might be tricky since it requires a newer version of Go than focal has. Maybe we could make this for hirsute+ only.

**Review by jacobgkau — APPROVED** [review]
If that's the route we want to go, that will work. This together with https://github.com/pop-os/libnvidia-container/pull/4 gets the Tensorflow GPU examples in the support article working on 21.04.
